### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by yalh76**
Fix https://github.com/YunoHost-Apps/webtrees_ynh/issues/3

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/webtrees_ynh%20PR9%20(yalh76)/)

### CODE REVIEW

**Comment by yalh76** [comment]
@anmol26s and @toitoinebzh 

I've merged both PR in this one. So Anmol just have to merge it to testing when ready

**Comment by toitoinebzh** [comment]
Great :)

**Comment by anmol26s** [comment]
Build is failing?

**Comment by yalh76** [comment]
> 
> 
> Build is failing?

Yes, still the same error:
image

It's caused by webtrees himself....

**Comment by yalh76** [comment]
I've seen there is a 2.0.0 ^^

**Comment by toitoinebzh** [comment]
... since 7th of december
https://github.com/fisharebest/webtrees/releases/tag/2.0.0

do you think we should just update this script ? or start a new one ?

**Comment by yalh76** [comment]
It's better to update the script.

**Pull request merged**
